### ISSUE TITLE
Missing cwmacros_fd.txt on initial load. (23.5.30)

### ISSUE THREAD

**Issue by ATCUSA** [mbridak/FieldDayLogger#29]
**Problem**
Initial run fails to launch. The cwmacros_fd.txt file doesn't seem to be getting made on first load and is throwing an exception that it can't be found. This is just on 23.5.30 and works on 23.4.8.

**Work Around**
I made it work by running `touch cwmacros_fd.txt` before initial run.

**Error Message**
Traceback (most recent call last):
  File "/home/acole/.local/share/virtualenvs/fdlogger-JbRCUJ2g/bin/fdlogger", line 5, in <module>
    from fdlogger.__main__ import run
  File "/home/acole/.local/share/virtualenvs/fdlogger-JbRCUJ2g/lib/python3.10/site-packages/fdlogger/__main__.py", line 2591, in <module>
    window.read_cw_macros()
  File "/home/acole/.local/share/virtualenvs/fdlogger-JbRCUJ2g/lib/python3.10/site-packages/fdlogger/__main__.py", line 752, in read_cw_macros
    copyfile(data_path, "./cwmacros_fd.txt")
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/acole/.local/share/virtualenvs/fdlogger-JbRCUJ2g/lib/python3.10/site-packages/fdlogger/data/cwmacros_fd.txt'

**Desktop (please complete the following information):**
 - OS: Lunix Kubuntu
 - Version: 22.04

**Comment by mbridak** [comment]
Ah. Lemme pull pull that out of the git garbage, and put it back.

**Comment by mbridak** [comment]
okay, for some reason it was in my gitignore file, so I thought I didn't need it...
Fixed and pushed to pypi.

Thanks for pointing it out!

**Comment by ATCUSA** [comment]
Works great now. Thanks.
