### ISSUE TITLE
"error: metadata-generation-failed" on Install

### ISSUE THREAD

**Issue by dbrianhendrix** [mbridak/FieldDayLogger#42]
I am getting the following error message after trying to install fdlogger on AlmaLinux 9.4 on a Raspberry Pi 5:

[n0dbh@n0dbh ~]$ pip install fdlogger
Defaulting to user installation because normal site-packages is not writeable
Collecting fdlogger
  Using cached fdlogger-24.5.25-py3-none-any.whl.metadata (22 kB)
Collecting PyQt5 (from fdlogger)
  Using cached PyQt5-5.15.10.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
      Traceback (most recent call last):
        File "/home/n0dbh/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/n0dbh/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/n0dbh/.local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-5tjzu6r5/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/tmp/pip-build-env-5tjzu6r5/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 92, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-5tjzu6r5/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 587, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 68, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-5tjzu6r5/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 51, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-5tjzu6r5/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/tmp/pip-build-env-5tjzu6r5/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 50, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by dbrianhendrix** [comment]
I’m using AlmaLinux 9.4 which is not Debian. It doesn’t install anything via apt. It is rpm based and binary copy of Red Hat.


D. Brian Hendrix
veteran  |  mac guy  |  birder  |  coffee snob

Tennessee Naturalist, first
Senior Linux Engineer, second

615.336.4573
***@***.*** ***@***.***>
￼

**Comment by dbrianhendrix** [comment]
You’re on VACATION! This can wait!


D. Brian Hendrix
veteran  |  mac guy  |  birder  |  coffee snob

Tennessee Naturalist, first
Senior Linux Engineer, second

615.336.4573
***@***.*** ***@***.***>
￼

**Comment by mbridak** [comment]
Okay. The same concept applies to other distros and their packaging methods.
You would use whatever package manager available to install the available
pyqt5 package before pip installing fdlogger.
